// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/base': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/base').default>>>>
    }
    '/api/user/all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/all').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-chatgpt/dist/runtime/server/api/chat').default>>>>
    }
    '/api/chat-completion': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-chatgpt/dist/runtime/server/api/chat-completion').default>>>>
    }
    '/_nitro/openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../#internal/nitro/routes/openapi').default>>>>
    }
    '/_nitro/swagger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../#internal/nitro/routes/swagger').default>>>>
    }
  }
}
export {}